# OpenFileBot launch4j runtime config
-Dapplication.dir="%APPDATA%\openfilebot"
-Dapplication.deployment=appx
-Dapplication.update=skip

# put all temporary files here
-Djava.io.tmpdir="%APPDATA%\openfilebot\tmp"

# network settings
-Djava.net.useSystemProxies=true

# use Windows Shell for move/copy operations
-DuseNativeShell=true

# use NTFS extended attributes for storing metadata
-DuseExtendedFileAttributes=true
-DuseCreationDate=false

# look for executables in the application folder
-Dorg.openfilebot.AcoustID.fpcalc="%EXEDIR%\fpcalc.exe"

# look for native libraries in the application folder
-Djna.library.path="%EXEDIR%"
-Djna.boot.library.path="%EXEDIR%"
-Djava.library.path="%EXEDIR%"

# make sure to use the bundled JNA library
-Djna.nosys=true
-Djna.nounpack=true

# disable HW acceleration
-Dsun.java2d.d3d=false
-Dprism.order=sw

# reduce default logging
-Djava.util.logging.config.file="%EXEDIR%\logging.properties"

# force Application User Model ID for Windows package
-Dorg.openfilebot.AppUserModelID=@{microsoft.application.name}

# support JAVA_OPTS environment variable
%JAVA_OPTS%

# support OPENFILEBOT_OPTS environment variable (preferred)
%OPENFILEBOT_OPTS%

# support FILEBOT_OPTS environment variable (legacy fallback)
%FILEBOT_OPTS%
