# application settings
application.name: openfilebot
application.version: 0.9.1
application.revision: @{revision}

# application updates
update.url: https://api.github.com/repos/masterxq/openfilebot/releases/latest

# base URL for resolving script resources
github.stable: https://github.com/masterxq/openfilebot/releases/latest/download/m1.jar.xz
github.master: https://github.com/masterxq/openfilebot

# native links
link.mas: https://github.com/masterxq/openfilebot/releases
link.mws: https://github.com/masterxq/openfilebot/releases

# online help
link.intro: https://github.com/masterxq/openfilebot
link.forums: https://github.com/masterxq/openfilebot
link.twitter: https://github.com/masterxq/openfilebot
link.facebook: https://github.com/masterxq/openfilebot
link.faq: https://github.com/masterxq/openfilebot
link.bugs: https://github.com/masterxq/openfilebot/issues
link.channel: https://github.com/masterxq/openfilebot
link.help: https://github.com/masterxq/openfilebot
link.help.mas: https://github.com/masterxq/openfilebot

# api keys
apikey.fanart.tv: 780b986b22c35e6f7a134a2f392c2deb
apikey.thetvdb: 694FAD89942D3827
apikey.themoviedb: 66308fb6e3fd850dde4c7d21df2e8306
apikey.omdb: 49d311ec
apikey.acoustid: 0B3qZnQc
apikey.anidb: filebot
apikey.opensubtitles: FileBot

# api keys
com.apikey.fanart.tv: 780b986b22c35e6f7a134a2f392c2deb
com.apikey.thetvdb: 5F6E873A88CF70D9
com.apikey.themoviedb: 28bce8224bd3282a41bec4c5df528249
com.apikey.omdb: 49d311ec
com.apikey.acoustid: VCujaMw9
com.apikey.anidb: filebotappstore
com.apikey.opensubtitles: FileBot-AppStore
